### ISSUE TITLE
Data race in spyder

### ISSUE THREAD

**Issue by ParthDesai** [bulletind/spyder#15]
==================
WARNING: DATA RACE
Write by goroutine 17:
  reflect.memmove()
      /usr/lib/go/src/pkg/reflect/value.go:39 +0x17a
  reflect.Value.Set()
      /usr/lib/go/src/pkg/reflect/value.go:1387 +0xfc
  gopkg.in/mgo.v2/bson.(*decoder).readDocTo()
      /home/parth/go_projects/src/gopkg.in/mgo.v2/bson/decode.go:202 +0x18e3
  gopkg.in/mgo.v2/bson.Unmarshal()
      /home/parth/go_projects/src/gopkg.in/mgo.v2/bson/bson.go:505 +0x26a
  gopkg.in/mgo%2ev2.(*Iter).Next()
      /home/parth/go_projects/src/gopkg.in/mgo.v2/session.go:3057 +0x74e
  github.com/changer/spyder/db.TailOps()
      /home/parth/go_projects/src/github.com/changer/spyder/db/gtm.go:75 +0x207

Previous read by goroutine 77:
  github.com/changer/spyder/plugins/history.CreateBasicHistory()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/history/history.go:11 +0x7d
  github.com/changer/spyder/plugins/history.CreateUpdateHistory()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/history/history.go:24 +0x4a
  github.com/changer/spyder/plugins/history.HistoryHandler.Handle()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/history/historyhandler.go:47 +0x897

Goroutine 17 (running) created at:
  github.com/changer/spyder/db.tail()
      /home/parth/go_projects/src/github.com/changer/spyder/db/gtm.go:108 +0xa9
  github.com/changer/spyder/db.ReadOplog()
      /home/parth/go_projects/src/github.com/changer/spyder/db/oplog.go:28 +0xd0
  main.main()
      /home/parth/go_projects/src/github.com/changer/spyder/main.go:38 +0x5ec

Goroutine 77 (running) created at:
  github.com/changer/spyder/plugins.func·001()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/historylistener.go:20 +0x207
==================
==================
WARNING: DATA RACE
Write by goroutine 17:
  reflect.memmove()
      /usr/lib/go/src/pkg/reflect/value.go:39 +0x17a
  reflect.Value.Set()
      /usr/lib/go/src/pkg/reflect/value.go:1387 +0xfc
  gopkg.in/mgo.v2/bson.(*decoder).readDocTo()
      /home/parth/go_projects/src/gopkg.in/mgo.v2/bson/decode.go:202 +0x18e3
  gopkg.in/mgo.v2/bson.Unmarshal()
      /home/parth/go_projects/src/gopkg.in/mgo.v2/bson/bson.go:505 +0x26a
  gopkg.in/mgo%2ev2.(*Iter).Next()
      /home/parth/go_projects/src/gopkg.in/mgo.v2/session.go:3057 +0x74e
  github.com/changer/spyder/db.TailOps()
      /home/parth/go_projects/src/github.com/changer/spyder/db/gtm.go:75 +0x207

Previous read by goroutine 77:
  github.com/changer/spyder/plugins/history.HistoryHandler.Handle()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/history/historyhandler.go:44 +0x73e

Goroutine 17 (running) created at:
  github.com/changer/spyder/db.tail()
      /home/parth/go_projects/src/github.com/changer/spyder/db/gtm.go:108 +0xa9
  github.com/changer/spyder/db.ReadOplog()
      /home/parth/go_projects/src/github.com/changer/spyder/db/oplog.go:28 +0xd0
  main.main()
      /home/parth/go_projects/src/github.com/changer/spyder/main.go:38 +0x5ec

Goroutine 77 (running) created at:
  github.com/changer/spyder/plugins.func·001()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/historylistener.go:20 +0x207
==================
==================
WARNING: DATA RACE
Write by goroutine 17:
  reflect.memmove()
      /usr/lib/go/src/pkg/reflect/value.go:39 +0x17a
  reflect.Value.Set()
      /usr/lib/go/src/pkg/reflect/value.go:1387 +0xfc
  gopkg.in/mgo.v2/bson.(*decoder).readDocTo()
      /home/parth/go_projects/src/gopkg.in/mgo.v2/bson/decode.go:202 +0x18e3
  gopkg.in/mgo.v2/bson.Unmarshal()
      /home/parth/go_projects/src/gopkg.in/mgo.v2/bson/bson.go:505 +0x26a
  gopkg.in/mgo%2ev2.(*Iter).Next()
      /home/parth/go_projects/src/gopkg.in/mgo.v2/session.go:3057 +0x74e
  github.com/changer/spyder/db.TailOps()
      /home/parth/go_projects/src/github.com/changer/spyder/db/gtm.go:75 +0x207

Previous read by goroutine 77:
  github.com/changer/spyder/db.(*Fly).GetOrganization()
      /home/parth/go_projects/src/github.com/changer/spyder/db/fly.go:38 +0x3a
  github.com/changer/spyder/plugins/history.(*History).AttachUpdateSpec()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/history/history.go:19 +0x71
  github.com/changer/spyder/plugins/history.CreateUpdateHistory()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/history/history.go:25 +0xa5
  github.com/changer/spyder/plugins/history.HistoryHandler.Handle()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/history/historyhandler.go:47 +0x897

Goroutine 17 (running) created at:
  github.com/changer/spyder/db.tail()
      /home/parth/go_projects/src/github.com/changer/spyder/db/gtm.go:108 +0xa9
  github.com/changer/spyder/db.ReadOplog()
      /home/parth/go_projects/src/github.com/changer/spyder/db/oplog.go:28 +0xd0
  main.main()
      /home/parth/go_projects/src/github.com/changer/spyder/main.go:38 +0x5ec

Goroutine 77 (running) created at:
  github.com/changer/spyder/plugins.func·001()
      /home/parth/go_projects/src/github.com/changer/spyder/plugins/historylistener.go:20 +0x207
==================

**Comment by meson10** [comment]
Not applicable anymore since history is separated from spyder.
